# Generated by Django 5.2.1 on 2025-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Cédula de Identidad"
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=100, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=100, verbose_name="Primer Apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo Apellido",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "correo_electronico",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de Ingreso")),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario Base"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, verbose_name="Activo en la empresa"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "ordering": ["primer_apellido", "primer_nombre"],
            },
        ),
    ]
