# Generated by Django 5.2.1 on 2025-06-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0002_cargo_departamento_alter_colaborador_cargo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tipo de Evaluación"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción del Tipo de Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Evaluación",
                "verbose_name_plural": "Tipos de Evaluaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionClima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título de la Evaluación"
                    ),
                ),
                (
                    "puntaje_general",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje General del Clima",
                    ),
                ),
                (
                    "fortalezas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Principales Fortalezas"
                    ),
                ),
                (
                    "areas_mejora",
                    models.TextField(
                        blank=True, null=True, verbose_name="Áreas de Oportunidad"
                    ),
                ),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluaciones_clima/",
                        verbose_name="Informe Completo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.departamento",
                        verbose_name="Departamento Evaluado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Clima Organizacional",
                "verbose_name_plural": "Evaluaciones de Clima Organizacional",
                "ordering": ["-fecha_evaluacion", "departamento__nombre"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "evaluador",
                    models.CharField(max_length=100, verbose_name="Evaluador"),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje Obtenido",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios Generales"
                    ),
                ),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluaciones_desempeno/",
                        verbose_name="Documento Adjunto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_desempeno",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador Evaluado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Desempeño",
                "verbose_name_plural": "Evaluaciones de Desempeño",
                "ordering": ["-fecha_evaluacion", "colaborador__primer_apellido"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoOperativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(verbose_name="Fecha de Registro del Resultado"),
                ),
                (
                    "tipo_metrica",
                    models.CharField(
                        max_length=100,
                        verbose_name="Tipo de Métrica (ej. Ventas, Producción, Proyectos Completados)",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valor del Resultado",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios Adicionales"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados_operativos",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador Asociado",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.departamento",
                        verbose_name="Departamento Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Operativo",
                "verbose_name_plural": "Resultados Operativos",
                "ordering": [
                    "-fecha_registro",
                    "colaborador__primer_apellido",
                    "departamento__nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion360",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "evaluador",
                    models.CharField(
                        choices=[
                            ("Yo mismo", "Yo mismo"),
                            ("Supervisor Inmediato", "Supervisor Inmediato"),
                            ("Compañero de Trabajo", "Compañero de Trabajo"),
                            ("Subordinado", "Subordinado"),
                            ("Cliente", "Cliente"),
                            ("Proveedor", "Proveedor"),
                        ],
                        max_length=50,
                        verbose_name="¿Quién Evalúa?",
                    ),
                ),
                (
                    "p1_resuelve_problemas",
                    models.IntegerField(
                        verbose_name="¿Resuelve problemas de forma efectiva?"
                    ),
                ),
                (
                    "p2_resuelve_conflictos",
                    models.IntegerField(
                        verbose_name="¿Sabe resolver conflictos adecuadamente?"
                    ),
                ),
                (
                    "p3_respetuoso",
                    models.IntegerField(
                        verbose_name="¿Es respetuoso con el resto de los empleados?"
                    ),
                ),
                ("p4_empatia", models.IntegerField(verbose_name="¿Muestra empatía?")),
                (
                    "p5_sociable_comunicativo",
                    models.IntegerField(
                        verbose_name="¿Es sociable y se comunica de forma abierta y cercana con sus colegas?"
                    ),
                ),
                (
                    "p6_confiable",
                    models.IntegerField(
                        verbose_name="¿Es un compañero en quien se puede confiar?"
                    ),
                ),
                (
                    "p7_aporta_valor",
                    models.IntegerField(
                        verbose_name="¿Aporta valor y conocimiento al resto?"
                    ),
                ),
                (
                    "p8_actitud_proactiva_ayudar",
                    models.IntegerField(
                        verbose_name="¿Tiene una actitud proactiva a la hora de ayudar en el equipo?"
                    ),
                ),
                (
                    "p9_proactivo_ideas",
                    models.IntegerField(
                        verbose_name="¿Es proactivo para aportar ideas?"
                    ),
                ),
                (
                    "p10_iniciativa_proyectos",
                    models.IntegerField(
                        verbose_name="¿Toma la iniciativa en los proyectos?"
                    ),
                ),
                (
                    "p11_conoce_valores",
                    models.IntegerField(
                        verbose_name="¿Conoce y pone en práctica la misión y los valores de la empresa?"
                    ),
                ),
                (
                    "p12_comportamiento_etico",
                    models.IntegerField(
                        verbose_name="¿Demuestra un comportamiento ético y profesional?"
                    ),
                ),
                (
                    "p13_implica_cumple_plazos",
                    models.IntegerField(
                        verbose_name="¿Se implica en su trabajo y cumple los plazos?"
                    ),
                ),
                (
                    "p14_manejo_estres",
                    models.IntegerField(
                        verbose_name="¿Sabe manejarse en situaciones de estrés y de sobrecarga de trabajo?"
                    ),
                ),
                (
                    "p15_recibe_criticas_aprende",
                    models.IntegerField(
                        verbose_name="¿Recibe de forma positiva las críticas y los comentarios constructivos, ya sean positivos o negativos? ¿Aprende de sus errores?"
                    ),
                ),
                (
                    "p16_valora_otras_opiniones",
                    models.IntegerField(
                        verbose_name="¿Toma en cuenta y valora otras opiniones incluso si son distintas a las suyas?"
                    ),
                ),
                (
                    "p17_ideas_innovadoras",
                    models.IntegerField(
                        verbose_name="¿Aporta ideas innovadoras para alcanzar objetivos?"
                    ),
                ),
                (
                    "p18_practica_formacion_continua",
                    models.IntegerField(
                        verbose_name="¿Se muestra a favor y practica la formación continua como método de ayuda al crecimiento de la empresa?"
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios Adicionales"
                    ),
                ),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluaciones_360/",
                        verbose_name="Documento Adjunto",
                    ),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje Total",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_360",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador Evaluado",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="colaboradores.tipoevaluacion",
                        verbose_name="Tipo de Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación 360º",
                "verbose_name_plural": "Evaluaciones 360º",
                "ordering": ["-fecha_evaluacion", "colaborador__primer_apellido"],
                "unique_together": {("colaborador", "fecha_evaluacion", "evaluador")},
            },
        ),
    ]
