# Generated by Django 5.2.1 on 2025-06-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "colaboradores",
            "0003_tipoevaluacion_evaluacionclima_evaluaciondesempeno_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionObjetivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "periodo_evaluado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Período Evaluado (ej. Q1 2025, Mensual Ene-25)",
                    ),
                ),
                (
                    "evaluador",
                    models.CharField(
                        max_length=100, verbose_name="Evaluador del Objetivo"
                    ),
                ),
                ("objetivo_general", models.TextField(verbose_name="Objetivo General")),
                (
                    "tipo_medicion",
                    models.CharField(
                        choices=[
                            ("% Cumplimiento", "% Cumplimiento"),
                            ("Cantidad Cumplimiento", "Cantidad Cumplimiento"),
                            ("Logro", "Logro (si aplica, ej. sí/no)"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Medición",
                    ),
                ),
                (
                    "meta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Meta (Valor Esperado)",
                    ),
                ),
                (
                    "resultado_obtenido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Resultado Obtenido",
                    ),
                ),
                (
                    "puntuacion_final",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Puntuación del Colaborador (1-5)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones / Feedback"
                    ),
                ),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluaciones_objetivos/",
                        verbose_name="Documento Adjunto",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_objetivos",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador Evaluado",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="colaboradores.tipoevaluacion",
                        verbose_name="Tipo de Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación por Objetivos",
                "verbose_name_plural": "Evaluaciones por Objetivos",
                "ordering": ["-fecha_evaluacion", "colaborador__primer_apellido"],
                "unique_together": {
                    ("colaborador", "fecha_evaluacion", "objetivo_general")
                },
            },
        ),
    ]
