# Generated by Django 5.2.1 on 2025-06-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0004_evaluacionobjetivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacionobjetivos",
            name="puntuacion_final",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Puntuación del Colaborador (1-100)"
            ),
        ),
        migrations.CreateModel(
            name="EvaluacionClimaOrganizacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "rc1_directiva_coherente",
                    models.IntegerField(
                        verbose_name="1. El equipo directivo actúa de forma coherente con la estrategia y los objetivos de la organización."
                    ),
                ),
                (
                    "rc2_conoce_plan_estrategico",
                    models.IntegerField(
                        verbose_name="2. Conozco las directrices principales del plan estratégico."
                    ),
                ),
                (
                    "rc3_comparte_objetivos",
                    models.IntegerField(
                        verbose_name="3. Comparto los objetivos y las metas de esta organización."
                    ),
                ),
                (
                    "rc4_identifica_valores",
                    models.IntegerField(
                        verbose_name="4. Me identifico con los valores de la organización."
                    ),
                ),
                (
                    "rc5_comprometido_empresa",
                    models.IntegerField(
                        verbose_name="5. Me siento comprometido/a con esta empresa."
                    ),
                ),
                (
                    "rc6_desarrollar_carrera",
                    models.IntegerField(
                        verbose_name="6. Mi intención es desarrollar mi carrera profesional en esta empresa."
                    ),
                ),
                (
                    "rc7_mejorar_empresa_abierta",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="7. ¿Qué podríamos mejorar en la empresa? (Pregunta abierta)",
                    ),
                ),
                (
                    "rl1_genera_ilusion",
                    models.IntegerField(
                        verbose_name="1. Genera ilusión/motivación en el equipo."
                    ),
                ),
                (
                    "rl2_mantiene_ambiente",
                    models.IntegerField(
                        verbose_name="2. Se esfuerza en mantener un buen ambiente de trabajo."
                    ),
                ),
                (
                    "rl3_dedica_tiempo",
                    models.IntegerField(
                        verbose_name="3. Te dedica el tiempo cuando tienes alguna necesidad."
                    ),
                ),
                (
                    "rl4_lider_coherente",
                    models.IntegerField(
                        verbose_name="4. Es coherente entre lo que dice y lo que hace."
                    ),
                ),
                (
                    "rl5_comunica_prioridades",
                    models.IntegerField(
                        verbose_name="5. Comunica las prioridades de forma clara y se asegura que sean entendidas."
                    ),
                ),
                (
                    "rl6_efectividad_feedback",
                    models.IntegerField(
                        verbose_name="6. Que tan efectivos son los feedback que recibes."
                    ),
                ),
                (
                    "rl7_opinion_liderazgo_abierta",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="7. Cual es tu opinión acerca del liderazgo en el departamento (Pregunta abierta)",
                    ),
                ),
                (
                    "rpt1_recibio_herramientas",
                    models.IntegerField(
                        verbose_name="1. Al incorporarme a esta empresa, recibí las herramientas, accesos y materiales necesarios para realizar mi trabajo desde el primer día."
                    ),
                ),
                (
                    "rpt2_impacto_objetivos_global",
                    models.IntegerField(
                        verbose_name="2. Conozco cómo impactan mis objetivos en el plan global de la organización."
                    ),
                ),
                (
                    "rpt3_autonomia_trabajo",
                    models.IntegerField(
                        verbose_name="3. Tengo la autonomía suficiente para planificar y realizar mi trabajo."
                    ),
                ),
                (
                    "rpt4_feedback_ayuda_mejorar",
                    models.IntegerField(
                        verbose_name="4. El feedback que recibo sobre mi trabajo me ayuda a mejorar."
                    ),
                ),
                (
                    "rpt5_conoce_crecimiento_profesional",
                    models.IntegerField(
                        verbose_name="5. Conozco los pasos que debo seguir para crecer profesionalmente en esta organización."
                    ),
                ),
                (
                    "rpt6_formacion_ayuda",
                    models.IntegerField(
                        verbose_name="6. La formación que recibo me ayuda a mejorar en mi trabajo."
                    ),
                ),
                (
                    "rpt7_siente_valorado",
                    models.IntegerField(
                        verbose_name="7. Me siento valorado/a en mi puesto de trabajo."
                    ),
                ),
                (
                    "rpt8_concluye_trabajo_jornada",
                    models.IntegerField(
                        verbose_name="8. Puedo concluir mi trabajo dentro de la jornada laboral."
                    ),
                ),
                (
                    "rpt9_mejorar_puesto_abierta",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="9. Si pudieras mejorar algo en tu puesto de trabajo, ¿Qué seria? ¿Te harían falta otras herramientas? (Pregunta abierta)",
                    ),
                ),
                (
                    "rco1_ambiente_positivo",
                    models.IntegerField(
                        verbose_name="1. Valoro positivamente el ambiente de trabajo."
                    ),
                ),
                (
                    "rco2_trabajo_equipo",
                    models.IntegerField(
                        verbose_name="2. En esta empresa trabajamos en equipo."
                    ),
                ),
                (
                    "rco3_conoce_otros_departamentos",
                    models.IntegerField(
                        verbose_name="3. Conozco el trabajo que se desempeña en los otros departamentos de la empresa."
                    ),
                ),
                (
                    "rco4_fomenta_agilidad",
                    models.IntegerField(
                        verbose_name="4. En mi empresa se fomenta la agilidad de los procesos internos."
                    ),
                ),
                (
                    "rco5_comunicaciones_claras",
                    models.IntegerField(
                        verbose_name="5. Las comunicaciones internas llegan de forma clara, sincera y puntual."
                    ),
                ),
                (
                    "rco6_comentarios_companeros_abierta",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="6. En relación con tus compañeros de trabajo y tu día a día ejerciendo tus funciones, ¿Qué nos podrías comentar? (Pregunta abierta)",
                    ),
                ),
                (
                    "rcl1_conoce_necesidades",
                    models.IntegerField(
                        verbose_name="1. Conozco bien las necesidades de nuestros clientes."
                    ),
                ),
                (
                    "rcl2_clientes_satisfechos",
                    models.IntegerField(
                        verbose_name="2. Nuestros clientes están satisfechos con el trato que reciben por parte de la empresa."
                    ),
                ),
                (
                    "rcl3_recomendaciones_tenidas_cuenta",
                    models.IntegerField(
                        verbose_name="3. Las recomendaciones de nuestros clientes son tenidas en cuenta."
                    ),
                ),
                (
                    "rcl4_compagina_objetivos_calidad",
                    models.IntegerField(
                        verbose_name="4. Sabemos compaginar los objetivos económicos y la calidad de los servicios/productos que proporcionamos a nuestros clientes."
                    ),
                ),
                (
                    "puntaje_total_cerradas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Puntaje Total Preguntas Cerradas",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="colaboradores.departamento",
                        verbose_name="Departamento del Colaborador",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="colaboradores.tipoevaluacion",
                        verbose_name="Tipo de Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Clima Organizacional",
                "verbose_name_plural": "Evaluaciones de Clima Organizacional",
                "ordering": ["-fecha_evaluacion", "departamento__nombre"],
            },
        ),
    ]
